name: Laravel CI

on:
  push:
    branches: [ "main" ]
  schedule:
      - cron: '0 0 * * *'
#   pull_request:
#     branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.1'
    - uses: actions/checkout@v3
    - name: Install composer dependencies
      run: |
        composer install --no-scripts
    - name: Prepare Laravel Application
      run: |
        cp .env.ci .env
        php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Create Database
      run: |
        mkdir -p database
        touch database/database.sqlite
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: vendor/bin/phpunit
    - name: Check the duplicate code in app directory
      run: ./vendor/bin/phpcpd app/ --min-lines=5 --min-tokens=10
    - name: Perform phpmd script
      run: ./vendor/bin/phpmd app/ github phpmdrules.xml
